version: '3.3'

services:
  web:
    image: nginx:${VERSION_NGINX}
    container_name: ${PRODUCT_NAME}_web
    volumes:
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./bedrock/web:$WP_ROOT_DIR"
      - "./log/web:/var/log/nginx"
      - "./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "${NGINX_HTTP_PORTS}:80"
      - "${NGINX_HTTPS_PORTS}:443"
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$WP_ROOT_DIR' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - WP_ROOT_DIR=${WP_ROOT_DIR}
    depends_on:
      - db
      - php
  php:
    build:
      context: "./build/php/"
      args:
        - VERSION=${VERSION_PHP}
    container_name: ${PRODUCT_NAME}_php
    volumes:
      - "./config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./bedrock:/var/www"
      - "./bedrock/web/:$WP_ROOT_DIR"
    restart: always
  composer:
    image: composer:${VERSION_COMPOSER}
    volumes:
      - "./bedrock:/app"
    command: install
  db:
    image: mysql:${VERSION_SQL}
    command:
      - "--innodb-use-native-aio=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - "${MYSQL_PORTS}:3306"
    container_name: ${PRODUCT_NAME}_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./db/data:/var/lib/mysql"
