version: '3.3'

services:
  web:
    image: nginx:${VERSION_NGINX}
    container_name: ${PRODUCT_NAME}_web
    volumes:
      - "./${BEDROCK_DIR}:${WP_ROOT_DIR}"
      - "./log/web:/var/log/nginx"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./certs:/etc/nginx/ssl"
    ports:
      - "${NGINX_HTTP_PORTS}:80"
      - "${NGINX_HTTPS_PORTS}:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - WP_ROOT_DIR=${WP_ROOT_DIR}/web
      - UPLOAD_FILESIZE=${UPLOAD_FILESIZE}
      - SSL_KEY=${SSL_KEY}
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$WP_ROOT_DIR $$UPLOAD_FILESIZE $$SSL_KEY' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - db
      - php
  php:
    build:
      context: "./build/php/"
      args:
        - VERSION=${VERSION_PHP}
    container_name: ${PRODUCT_NAME}_php
    volumes:
      - "./config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./${BEDROCK_DIR}:${WP_ROOT_DIR}"
    restart: always
    environment:
      - UPLOAD_FILESIZE=${UPLOAD_FILESIZE}
      - MEMORY_LIMIT=${MEMORY_LIMIT}
      - MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME}
  composer:
    image: composer:${VERSION_COMPOSER}
    volumes:
      - "$PWD/${BEDROCK_DIR}:/app"
    command: install
  db:
    image: mysql:${VERSION_SQL}
    command:
      - "--innodb-use-native-aio=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    ports:
      - "${MYSQL_PORTS}:3306"
    container_name: ${PRODUCT_NAME}_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./db/data:/var/lib/mysql"
    user: ${LOCAL_USER}:${LOCAL_GROUP}
